package crucigrama;
import javax.swing.JOptionPane;
/**
 *
 * @author rafael
 */
public class N_dificil extends javax.swing.JFrame {
    /**
     * Creates new form N_dificil
     */
    public N_dificil() {
        initComponents();
        funran();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        V1v1 = new javax.swing.JTextField();
        V1a1 = new javax.swing.JTextField();
        V1r1 = new javax.swing.JTextField();
        V1i1 = new javax.swing.JTextField();
        V1a2 = new javax.swing.JTextField();
        V1b1 = new javax.swing.JTextField();
        V1l1 = new javax.swing.JTextField();
        V1e1 = new javax.swing.JTextField();
        V1s1 = new javax.swing.JTextField();
        H1b1 = new javax.swing.JTextField();
        V2s1 = new javax.swing.JTextField();
        H1t1 = new javax.swing.JTextField();
        H1r1 = new javax.swing.JTextField();
        H1a1 = new javax.swing.JTextField();
        H1c1 = new javax.swing.JTextField();
        H1c2 = new javax.swing.JTextField();
        V3i1 = new javax.swing.JTextField();
        H1o1 = new javax.swing.JTextField();
        H1n1 = new javax.swing.JTextField();
        V2w1 = new javax.swing.JTextField();
        V2i1 = new javax.swing.JTextField();
        V2t1 = new javax.swing.JTextField();
        V2c1 = new javax.swing.JTextField();
        V2h1 = new javax.swing.JTextField();
        H2e1 = new javax.swing.JTextField();
        H2r1 = new javax.swing.JTextField();
        H2e2 = new javax.swing.JTextField();
        H2n1 = new javax.swing.JTextField();
        H2c1 = new javax.swing.JTextField();
        H2i1 = new javax.swing.JTextField();
        H2a1 = new javax.swing.JTextField();
        V3c1 = new javax.swing.JTextField();
        V3c2 = new javax.swing.JTextField();
        V3l1 = new javax.swing.JTextField();
        V3o1 = new javax.swing.JTextField();
        V3s1 = new javax.swing.JTextField();
        H4l1 = new javax.swing.JTextField();
        H4a1 = new javax.swing.JTextField();
        H4s1 = new javax.swing.JTextField();
        H4e1 = new javax.swing.JTextField();
        H3p1 = new javax.swing.JTextField();
        H3o1 = new javax.swing.JTextField();
        H3i1 = new javax.swing.JTextField();
        H3m1 = new javax.swing.JTextField();
        H3o2 = new javax.swing.JTextField();
        H3r1 = new javax.swing.JTextField();
        H3f1 = new javax.swing.JTextField();
        V4i1 = new javax.swing.JTextField();
        H3s1 = new javax.swing.JTextField();
        H3m2 = new javax.swing.JTextField();
        V5o1 = new javax.swing.JTextField();
        V4u1 = new javax.swing.JTextField();
        V4n1 = new javax.swing.JTextField();
        V4c1 = new javax.swing.JTextField();
        V4f1 = new javax.swing.JTextField();
        V4o1 = new javax.swing.JTextField();
        V4n2 = new javax.swing.JTextField();
        V4e1 = new javax.swing.JTextField();
        V4s1 = new javax.swing.JTextField();
        V5m1 = new javax.swing.JTextField();
        V5e1 = new javax.swing.JTextField();
        V5t1 = new javax.swing.JTextField();
        V5d1 = new javax.swing.JTextField();
        V5o2 = new javax.swing.JTextField();
        V5s1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelIntentos = new javax.swing.JLabel();
        LabelLimite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setResizable(false);

        V1v1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1v1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1v1.setName("V1v1"); // NOI18N
        V1v1.setNextFocusableComponent(V1a1);

        V1a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1a1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1a1.setName("V1a1"); // NOI18N
        V1a1.setNextFocusableComponent(V1r1);

        V1r1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1r1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1r1.setName("V1r1"); // NOI18N
        V1r1.setNextFocusableComponent(V1i1);

        V1i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1i1.setName("V1i1"); // NOI18N
        V1i1.setNextFocusableComponent(V1a2);

        V1a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1a2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1a2.setName("V1a2"); // NOI18N
        V1a2.setNextFocusableComponent(V1b1);

        V1b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1b1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1b1.setName("V1b1"); // NOI18N
        V1b1.setNextFocusableComponent(V1l1);

        V1l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1l1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1l1.setName("V1l1"); // NOI18N
        V1l1.setNextFocusableComponent(V1e1);

        V1e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1e1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1e1.setName("V1e1"); // NOI18N
        V1e1.setNextFocusableComponent(V1s1);

        V1s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V1s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V1s1.setName("V1s1"); // NOI18N

        H1b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1b1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V2s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2s1.setName("V2s1"); // NOI18N
        V2s1.setNextFocusableComponent(V2w1);

        H1t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H1r1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1r1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H1a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1a1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H1c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1c1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H1c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1c2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V3i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3i1.setName("V3i1"); // NOI18N
        V3i1.setNextFocusableComponent(V3c2);

        H1o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1o1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H1n1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H1n1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V2w1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2w1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2w1.setName("V2w1"); // NOI18N
        V2w1.setNextFocusableComponent(V2i1);

        V2i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2i1.setName("V2i1"); // NOI18N
        V2i1.setNextFocusableComponent(V2t1);

        V2t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2t1.setName("V2t1"); // NOI18N
        V2t1.setNextFocusableComponent(V2c1);

        V2c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2c1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2c1.setName("V2c1"); // NOI18N
        V2c1.setNextFocusableComponent(V2h1);

        V2h1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V2h1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V2h1.setName("V2h1"); // NOI18N

        H2e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2e1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2r1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2r1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2e2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2e2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2n1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2n1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2c1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H2a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H2a1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V3c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3c1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3c1.setName("V3c1"); // NOI18N
        V3c1.setNextFocusableComponent(V3i1);

        V3c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3c2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3c2.setName("V3c2"); // NOI18N
        V3c2.setNextFocusableComponent(V3l1);

        V3l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3l1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3l1.setName("V3l1"); // NOI18N
        V3l1.setNextFocusableComponent(V3o1);

        V3o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3o1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3o1.setName("V3o1"); // NOI18N
        V3o1.setNextFocusableComponent(V3s1);

        V3s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V3s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V3s1.setName("V3s1"); // NOI18N

        H4l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H4l1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H4a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H4a1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H4s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H4s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H4e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H4e1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3p1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3o1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3m1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3m1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3o2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3o2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3r1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3r1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3f1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V4i1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4i1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4i1.setNextFocusableComponent(V4o1);

        H3s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        H3m2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        H3m2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V5o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5o1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5o1.setName("V5o1"); // NOI18N
        V5o1.setNextFocusableComponent(V5d1);

        V4u1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4u1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4u1.setName("V4u1"); // NOI18N
        V4u1.setNextFocusableComponent(V4n1);

        V4n1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4n1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4n1.setName("V4n1"); // NOI18N
        V4n1.setNextFocusableComponent(V4c1);

        V4c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4c1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4c1.setName("V4c1"); // NOI18N
        V4c1.setNextFocusableComponent(V4i1);

        V4f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4f1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4f1.setName("V4f1"); // NOI18N
        V4f1.setNextFocusableComponent(V4u1);

        V4o1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4o1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4o1.setName("V4o1"); // NOI18N
        V4o1.setNextFocusableComponent(V4n2);

        V4n2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4n2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4n2.setName("V4n2"); // NOI18N
        V4n2.setNextFocusableComponent(V4e1);

        V4e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4e1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V4e1.setNextFocusableComponent(V4s1);

        V4s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V4s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        V5m1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5m1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5m1.setName("V5m1"); // NOI18N
        V5m1.setNextFocusableComponent(V5e1);

        V5e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5e1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5e1.setName("V5e1"); // NOI18N
        V5e1.setNextFocusableComponent(V5t1);

        V5t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5t1.setName("V5t1"); // NOI18N
        V5t1.setNextFocusableComponent(V5o1);

        V5d1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5d1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5d1.setName("V5d1"); // NOI18N
        V5d1.setNextFocusableComponent(V5o2);

        V5o2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5o2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        V5o2.setName("V5s1"); // NOI18N
        V5o2.setNextFocusableComponent(V5s1);

        V5s1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        V5s1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("VERTICAL:\n1.Sirven para almacenar datos\n2.Se usa para varios casos\n3.Nos ayuda a repetir cosas\n4.Solo hace acciones\n5.Hace acciones y devuelve un valor\nHORIZONTAL:\n1.Esta relacionado con la clase, pero \"Se hace de diferente forma\"\n2.Gracias a \"\" las clases hijas obtienen atributos de la clase padre\n3.Este concepto no existe sin la HERENCIA\n4.Es un paradigma de la POO, es una plantilla");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("1");

        jLabel2.setText("2");

        jLabel3.setText("3");

        jLabel4.setText("4");

        jLabel5.setText("5");

        jLabel6.setText("1");

        jLabel7.setText("2");

        jLabel8.setText("3");

        jLabel9.setText("4");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("COMPARAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelIntentos.setText("INTENTOS 0");

        LabelLimite.setText("LIMITE 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(557, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(V1v1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V1s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(V1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(V1r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(V1i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(V1a2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(V1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(V1l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(V2s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(H1t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(H1r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(H1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(V2i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                                                        .addComponent(jLabel8)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(H3p1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(H3o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(H1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(H1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(13, 13, 13)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel9))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(V2w1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(V2t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(V2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(V3l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H3i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H3m1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H3o2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H3r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H3f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(V3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H4l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H4a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H4s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H4e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(V3i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H1o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(H1n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(V3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(V3o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(V3s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(V2h1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2e2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(H2a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(V1e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(197, 197, 197)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V4i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(H3s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(H3m2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(V4u1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V4n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V4c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V4o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V4n2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V4e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(V5s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5o2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5d1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(V5m1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(V4s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(V4f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(LabelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(V4f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(V1v1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(V3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(H4l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(H4a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(H4s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(H4e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(V4u1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(V5m1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V3i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H1n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2w1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V3l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3p1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3m1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3o2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3f1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3m2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1a2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V3o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4o1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5d1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V3s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4n2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5o2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V2h1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2r1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2e2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2n1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2i1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2a1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V5s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V1e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V4s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V1s1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int intento=0;
    public int limite;
    private void funran(){
        
        this.limite=Integer.parseInt(Math.round(Math.random()*10)+"");
        LabelLimite.setText("LIMITE "+this.limite);
    }
    public boolean VVariables(){
        //Variables
        boolean valor=false;
        char[] Variables=new char[9];
        if (V1v1.getText().toUpperCase().equals("V")) {
            V1v1.setEnabled(false);
            Variables[0]='V';
        }
        if (V1a1.getText().toUpperCase().equals("A")) {
            V1a1.setEnabled(false);
            Variables[1]='A';
        }
        if (V1r1.getText().toUpperCase().equals("R")) {
            V1r1.setEnabled(false);
            Variables[2]='R';
        }
        if (V1i1.getText().toUpperCase().equals("I")) {
            V1i1.setEnabled(false);
            Variables[3]='I';
        }
        if (V1a2.getText().toUpperCase().equals("A")) {
            V1a2.setEnabled(false);
            Variables[4]='A';
        }
        if (V1b1.getText().toUpperCase().equals("B")) {
            V1b1.setEnabled(false);
            Variables[5]='B';
        }
        if (V1l1.getText().toUpperCase().equals("L")) {
            V1l1.setEnabled(false);
            Variables[6]='L';
        }
        if (V1e1.getText().toUpperCase().equals("E")) {
            V1e1.setEnabled(false);
            Variables[7]='E';
        }
        if (V1s1.getText().toUpperCase().equals("S")) {
            V1s1.setEnabled(false);
            Variables[8]='S';
        }
        
        if (Variables[0]=='V' && Variables[1]=='A' && Variables[2]=='R' && Variables[3]=='I' && Variables[4]=='A' && Variables[5]=='B' && Variables[6]=='L' && Variables[7]=='E' && Variables[8]=='S') {
            valor=true;
        }
        return valor;
    }
    public boolean VSwicth(){
        char[] Switch=new char[6];
        boolean valor=false;
        if (V2s1.getText().toUpperCase().equals("S")) {
            V2s1.setEnabled(false);
            Switch[0]='S';
        }
        if (V2w1.getText().toUpperCase().equals("W")) {
            V2w1.setEnabled(false);
            Switch[1]='W';
        }
        if (V2i1.getText().toUpperCase().equals("I")) {
            V2i1.setEnabled(false);
            Switch[2]='I';
        }
        if (V2t1.getText().toUpperCase().equals("T")) {
            V2t1.setEnabled(false);
            Switch[3]='T';
        }
        if (V2c1.getText().toUpperCase().equals("C")) {
            V2c1.setEnabled(false);
            Switch[4]='C';
        }
        if (V2h1.getText().toUpperCase().equals("H")) {
            V2h1.setEnabled(false);
            Switch[5]='H';
        }
        
        if (Switch[0]=='S' && Switch[1]=='W' && Switch[2]=='I' && Switch[3]=='T' && Switch[4]=='C' && Switch[5]=='H' ) {
            valor=true;
        }
        return valor;
    }
    public boolean VCiclos(){
        boolean valor=false;
        char[] Ciclos=new char[6];
        if (V3c1.getText().toUpperCase().equals("C")) {
            V3c1.setEnabled(false);
            Ciclos[0]='C';
        }
        if (V3i1.getText().toUpperCase().equals("I")) {
            V3i1.setEnabled(false);
            Ciclos[1]='I';
        }
        if (V3c2.getText().toUpperCase().equals("C")) {
            V3c2.setEnabled(false);
            Ciclos[2]='C';
        }
        if (V3l1.getText().toUpperCase().equals("L")) {
            V3l1.setEnabled(false);
            Ciclos[3]='L';
        }
        if (V3o1.getText().toUpperCase().equals("O")) {
            V3o1.setEnabled(false);
            Ciclos[4]='O';
        }
        if (V3s1.getText().toUpperCase().equals("S")) {
            V3s1.setEnabled(false);
            Ciclos[5]='S';
        }
        
        if (Ciclos[0]=='C' && Ciclos[1]=='I' && Ciclos[2]=='C' && Ciclos[3]=='L' && Ciclos[4]=='O' && Ciclos[5]=='S' ) {
            valor=true;
        }
        return valor;
    }
    public boolean VFunciones(){
        boolean valor=false;
        char[] Funciones=new char[9];
        if (V4f1.getText().toUpperCase().equals("F")) {
            V4f1.setEnabled(false);
            Funciones[0]='F';
        }
        if (V4u1.getText().toUpperCase().equals("U")) {
            V4u1.setEnabled(false);
            Funciones[1]='U';
        }
        if (V4n1.getText().toUpperCase().equals("N")) {
            V4n1.setEnabled(false);
            Funciones[2]='N';
        }
        if (V4c1.getText().toUpperCase().equals("C")) {
            V4c1.setEnabled(false);
            Funciones[3]='C';
        }
        if (V4i1.getText().toUpperCase().equals("I")) {
            V4i1.setEnabled(false);
            Funciones[4]='I';
        }
        if (V4o1.getText().toUpperCase().equals("O")) {
            V4o1.setEnabled(false);
            Funciones[5]='O';
        }
        if (V4n2.getText().toUpperCase().equals("N")) {
            V4n2.setEnabled(false);
            Funciones[6]='N';
        }
        if (V4e1.getText().toUpperCase().equals("E")) {
            V4e1.setEnabled(false);
            Funciones[7]='E';
        }
        if (V4s1.getText().toUpperCase().equals("S")) {
            V4s1.setEnabled(false);
            Funciones[8]='S';
        }
        
        if (Funciones[0]=='F' && Funciones[1]=='U' && Funciones[2]=='N' && Funciones[3]=='C' && Funciones[4]=='I' && Funciones[5]=='O' && Funciones[6]=='N' && Funciones[7]=='E' && Funciones[8]=='S') {
            valor=true;
        }
        
        return valor;
    }
    public boolean VMetodos(){
        boolean valor=false;
        char[] Metodos=new char[7];
        if (V5m1.getText().toUpperCase().equals("M")) {
            V5m1.setEnabled(false);
            Metodos[0]='M';
        }
        if (V5e1.getText().toUpperCase().equals("E")) {
            V5e1.setEnabled(false);
            Metodos[1]='E';
        }
        if (V5t1.getText().toUpperCase().equals("T")) {
            V5t1.setEnabled(false);
            Metodos[2]='T';
        }
        if (V5o1.getText().toUpperCase().equals("O")) {
            V5o1.setEnabled(false);
            Metodos[3]='O';
        }
        if (V5d1.getText().toUpperCase().equals("D")) {
            V5d1.setEnabled(false);
            Metodos[4]='D';
        }
        if (V5o2.getText().toUpperCase().equals("O")) {
            V5o2.setEnabled(false);
            Metodos[5]='O';
        }
        if (V5s1.getText().toUpperCase().equals("S")) {
            V5s1.setEnabled(false);
            Metodos[6]='S';
        }
        
        if (Metodos[0]=='M' && Metodos[1]=='E' && Metodos[2]=='T' && Metodos[3]=='O' && Metodos[4]=='D' && Metodos[5]=='O' && Metodos[6]=='S') {
            valor=true;
        }
        return valor;
    }
    public boolean HAbstraccion(){
        boolean valor=false;
        char[] Abstraccion=new char[11];
        if (V1a1.getText().toUpperCase().equals("A")) {
            V1a1.setEnabled(false);
            Abstraccion[0]='A';
        }
        if (H1b1.getText().toUpperCase().equals("B")) {
            H1b1.setEnabled(false);
            Abstraccion[1]='B';
        }
        if (V2s1.getText().toUpperCase().equals("S")) {
            V2s1.setEnabled(false);
            Abstraccion[2]='S';
        }
        if (H1t1.getText().toUpperCase().equals("T")) {
            H1t1.setEnabled(false);
            Abstraccion[3]='T';
        }
        if (H1r1.getText().toUpperCase().equals("R")) {
            H1r1.setEnabled(false);
            Abstraccion[4]='R';
        }
        if (H1a1.getText().toUpperCase().equals("A")) {
            H1a1.setEnabled(false);
            Abstraccion[5]='A';
        }
        if (H1c1.getText().toUpperCase().equals("C")) {
            H1c1.setEnabled(false);
            Abstraccion[6]='C';
        }
        if (H1c2.getText().toUpperCase().equals("C")) {
            H1c2.setEnabled(false);
            Abstraccion[7]='C';
        }
        if (V3i1.getText().toUpperCase().equals("I")) {
            V3i1.setEnabled(false);
            Abstraccion[8]='I';
        }
        if (H1o1.getText().toUpperCase().equals("O")) {
            H1o1.setEnabled(false);
            Abstraccion[9]='O';
        }
        if (H1n1.getText().toUpperCase().equals("N")) {
            H1n1.setEnabled(false);
            Abstraccion[10]='N';
        }
        
        if (Abstraccion[0]=='A' && Abstraccion[1]=='B' && Abstraccion[2]=='S' && Abstraccion[3]=='T' && Abstraccion[4]=='R' && Abstraccion[5]=='A' && Abstraccion[6]=='C' && Abstraccion[7]=='C' && Abstraccion[8]=='I' && Abstraccion[9]=='O' && Abstraccion[10]=='N') {
            valor=true;
        }
        return valor;
    }
    public boolean HHerencia(){
        boolean valor=false;
        char[] Herencia=new char[8];
        if (V2h1.getText().toUpperCase().equals("H")) {
            V2h1.setEnabled(false);
            Herencia[0]='H';
        }
        if (H2e1.getText().toUpperCase().equals("E")) {
            H2e1.setEnabled(false);
            Herencia[1]='E';
        }
        if (H2r1.getText().toUpperCase().equals("R")) {
            H2r1.setEnabled(false);
            Herencia[2]='R';
        }
        if (H2e2.getText().toUpperCase().equals("E")) {
            H2e2.setEnabled(false);
            Herencia[3]='E';
        }
        if (H2n1.getText().toUpperCase().equals("N")) {
            H2n1.setEnabled(false);
            Herencia[4]='N';
        }
        if (H2c1.getText().toUpperCase().equals("C")) {
            H2c1.setEnabled(false);
            Herencia[5]='C';
        }
        if (H2i1.getText().toUpperCase().equals("I")) {
            H2i1.setEnabled(false);
            Herencia[6]='I';
        }
        if (H2a1.getText().toUpperCase().equals("A")) {
            H2a1.setEnabled(false);
            Herencia[7]='A';
        }
        
        if (Herencia[0]=='H' && Herencia[1]=='E' && Herencia[2]=='R' && Herencia[3]=='E' && Herencia[4]=='N' && Herencia[5]=='C'&& Herencia[6]=='I' && Herencia[7]=='A' ) {
            valor=true;
        }
        return valor;
    }
    public boolean HPolimorfismo(){
        boolean valor=false;
        char[] Polimorfismoa=new char[12];
        if (H3p1.getText().toUpperCase().equals("P")) {
            H3p1.setEnabled(false);
            Polimorfismoa[0]='P';
        }
        if (H3o1.getText().toUpperCase().equals("O")) {
            H3o1.setEnabled(false);
            Polimorfismoa[1]='O';
        }
        if (V3l1.getText().toUpperCase().equals("L")) {
            V3l1.setEnabled(false);
            Polimorfismoa[2]='L';
        }
        if (H3i1.getText().toUpperCase().equals("I")) {
            H3i1.setEnabled(false);
            Polimorfismoa[3]='I';
        }
        if (H3m1.getText().toUpperCase().equals("M")) {
            H3m1.setEnabled(false);
            Polimorfismoa[4]='M';
        }
        if (H3o2.getText().toUpperCase().equals("O")) {
            H3o2.setEnabled(false);
            Polimorfismoa[5]='O';
        }
        if (H3r1.getText().toUpperCase().equals("R")) {
            H3r1.setEnabled(false);
            Polimorfismoa[6]='R';
        }
        if (H3f1.getText().toUpperCase().equals("F")) {
            H3f1.setEnabled(false);
            Polimorfismoa[7]='F';
        }
        if (V4i1.getText().toUpperCase().equals("I")) {
            V4i1.setEnabled(false);
            Polimorfismoa[8]='I';
        }
        if (H3s1.getText().toUpperCase().equals("S")) {
            H3s1.setEnabled(false);
            Polimorfismoa[9]='S';
        }
        
        if (H3m2.getText().toUpperCase().equals("M")) {
            H3m2.setEnabled(false);
            Polimorfismoa[10]='M';
        }
        if (V5o1.getText().toUpperCase().equals("O")) {
            V5o1.setEnabled(false);
            Polimorfismoa[11]='O';
        }
        
        if (Polimorfismoa[0]=='P' && Polimorfismoa[1]=='O' && Polimorfismoa[2]=='L' && Polimorfismoa[3]=='I' && Polimorfismoa[4]=='M' && Polimorfismoa[5]=='O' && Polimorfismoa[6]=='R' && Polimorfismoa[7]=='F' && Polimorfismoa[8]=='I' && Polimorfismoa[9]=='S' && Polimorfismoa[10]=='M' && Polimorfismoa[11]=='O' ) {
            valor=true;
        }
        return valor;
    }
    public boolean HClase(){
        boolean valor=false;
        char[] Clase=new char[5];
        if (V3c1.getText().toUpperCase().equals("C")) {
            V3c1.setEnabled(false);
            Clase[0]='C';
        }
        if (H4l1.getText().toUpperCase().equals("L")) {
            H4l1.setEnabled(false);
            Clase[1]='L';
        }
        if (H4a1.getText().toUpperCase().equals("A")) {
            H4a1.setEnabled(false);
            Clase[2]='A';
        }
        if (H4s1.getText().toUpperCase().equals("S")) {
            H4s1.setEnabled(false);
            Clase[3]='S';
        }
        if (H4e1.getText().toUpperCase().equals("E")) {
            H4e1.setEnabled(false);
            Clase[4]='E';
        }
        
        if (Clase[0]=='C' && Clase[1]=='L' && Clase[2]=='A' && Clase[3]=='S' && Clase[4]=='E' ) {
            valor=true;
        }
        return valor;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        intento++;
        LabelIntentos.setText("INTENTOS "+intento);
        boolean var=VVariables();
        boolean var2=VSwicth();
        boolean var3=VCiclos();
        boolean var4=VFunciones();
        boolean var5=VMetodos();
        boolean var6=HAbstraccion();
        boolean var7=HHerencia();
        boolean var8=HPolimorfismo();
        boolean var9=HClase();
        if (this.intento<this.limite) {
            if (var && var2 && var3 && var4 && var5 && var6 && var7 && var8 && var9) {
            JOptionPane.showMessageDialog(this, "Felicidades lo hiciste en "+intento+" intentos");
            this.dispose();
             }
            else JOptionPane.showMessageDialog(this, "A donde tan rapido XD");
        }
        else {
            JOptionPane.showMessageDialog(this, "Game Over"); 
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_dificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField H1a1;
    private javax.swing.JTextField H1b1;
    private javax.swing.JTextField H1c1;
    private javax.swing.JTextField H1c2;
    private javax.swing.JTextField H1n1;
    private javax.swing.JTextField H1o1;
    private javax.swing.JTextField H1r1;
    private javax.swing.JTextField H1t1;
    private javax.swing.JTextField H2a1;
    private javax.swing.JTextField H2c1;
    private javax.swing.JTextField H2e1;
    private javax.swing.JTextField H2e2;
    private javax.swing.JTextField H2i1;
    private javax.swing.JTextField H2n1;
    private javax.swing.JTextField H2r1;
    private javax.swing.JTextField H3f1;
    private javax.swing.JTextField H3i1;
    private javax.swing.JTextField H3m1;
    private javax.swing.JTextField H3m2;
    private javax.swing.JTextField H3o1;
    private javax.swing.JTextField H3o2;
    private javax.swing.JTextField H3p1;
    private javax.swing.JTextField H3r1;
    private javax.swing.JTextField H3s1;
    private javax.swing.JTextField H4a1;
    private javax.swing.JTextField H4e1;
    private javax.swing.JTextField H4l1;
    private javax.swing.JTextField H4s1;
    private javax.swing.JLabel LabelIntentos;
    private javax.swing.JLabel LabelLimite;
    private javax.swing.JTextField V1a1;
    private javax.swing.JTextField V1a2;
    private javax.swing.JTextField V1b1;
    private javax.swing.JTextField V1e1;
    private javax.swing.JTextField V1i1;
    private javax.swing.JTextField V1l1;
    private javax.swing.JTextField V1r1;
    private javax.swing.JTextField V1s1;
    private javax.swing.JTextField V1v1;
    private javax.swing.JTextField V2c1;
    private javax.swing.JTextField V2h1;
    private javax.swing.JTextField V2i1;
    private javax.swing.JTextField V2s1;
    private javax.swing.JTextField V2t1;
    private javax.swing.JTextField V2w1;
    private javax.swing.JTextField V3c1;
    private javax.swing.JTextField V3c2;
    private javax.swing.JTextField V3i1;
    private javax.swing.JTextField V3l1;
    private javax.swing.JTextField V3o1;
    private javax.swing.JTextField V3s1;
    private javax.swing.JTextField V4c1;
    private javax.swing.JTextField V4e1;
    private javax.swing.JTextField V4f1;
    private javax.swing.JTextField V4i1;
    private javax.swing.JTextField V4n1;
    private javax.swing.JTextField V4n2;
    private javax.swing.JTextField V4o1;
    private javax.swing.JTextField V4s1;
    private javax.swing.JTextField V4u1;
    private javax.swing.JTextField V5d1;
    private javax.swing.JTextField V5e1;
    private javax.swing.JTextField V5m1;
    private javax.swing.JTextField V5o1;
    private javax.swing.JTextField V5o2;
    private javax.swing.JTextField V5s1;
    private javax.swing.JTextField V5t1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
